name: iac-scan

on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/iac-scan.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/iac-scan.yml'

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash
          echo "$HOME/.lacework/bin" >> $GITHUB_PATH

      - name: Configure Lacework CLI
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
        run: |
          lacework configure \
            -a "$LW_ACCOUNT_NAME" \
            -k "$LW_API_KEY" \
            -s "$LW_API_SECRET" \
            --noninteractive

      - name: Install IaC component
        run: lacework component install iac
        
      - name: Scan IaC (diagnostic)
        continue-on-error: true
        run: |
          mkdir -p reports
          lacework iac scan --upload \
            --directory infra \

      - name: Show summary
        if: always()
        run: |
          echo "## Lacework IaC Scan" >> $GITHUB_STEP_SUMMARY
          echo "Results uploaded as SARIF. Threshold: High." >> $GITHUB_STEP_SUMMARY
